name: rsv_replication
channels:
  - conda-forge
  - defaults
dependencies:
  # Python (forest data construction only)
  - python
  - numpy
  - pandas
  - geopandas
  - requests
  - rasterio
  - cartopy
  - pip
  - pip:
    - redivis

  # R
  - r-base
  - r-argparse
  - r-binsreg
  - r-data.table
  - r-dplyr
  - r-fixest
  - r-geosphere
  - r-ggplot2
  - r-ggpubr
  - r-ggtext
  - r-haven
  - r-igraph
  - r-latex2exp
  - r-lmtest
  - r-nnet
  - r-purrr
  - r-pROC
  - r-ranger
  - r-rcolorbrewer
  - r-readr
  - r-sandwich
  - r-scales
  - r-sf
  - r-stringr
  - r-tibble
  - r-tidyr
