name: rsv_replication
channels:
  - conda-forge
  - defaults
dependencies:
  # Python (forest data construction only)
  - python=3.11
  - numpy
  - pandas
  - geopandas
  - requests
  - rasterio
  - cartopy
  - pip
  - pip:
    - redivis

  # R
  - r-base
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-purrr
  - r-ggplot2
  - r-fixest
  - r-sf
  - r-readr
  - r-ggtext
  - r-latex2exp
  - r-scales
  - r-rcolorbrewer
  - r-knitr
  - r-kableextra
  - r-ranger
  - r-proc
  - r-argparse
